extern float lux;
extern int lamp_state;
extern const float TURN_ON_AT;
extern const float TURN_OFF_AT;
extern const float LAMP_ON_CONSUMPTION;
extern const float LAMP_OFF_CONSUMPTION;
void initialize_lamp();
void update_lux();
static float get_light();
float get_lux(int simulation);
static void config_lamp();
char * get_lamp_state();
void run_lamp();
void change_lamp_state(int new_state);
float get_lamp_consumption();