#!/usr/bin/env python3

import socket

HOST = '127.0.0.1'  # The server's hostname or IP address
PORT = 8877        # The port used by the server

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.connect((HOST, PORT))
    #s.sendall(b'exit')
    #s.sendall(b'get_from_db/2/1')
    s.sendall(b'lamp/state')
    #s.sendall(b'getall/2/1')
    data = s.recv(1024)

print('Received', repr(data.decode('utf-8')))
